# Generated by Django 4.1 on 2022-08-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(verbose_name='Ключ')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasksNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='TasksType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='TasksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rzn_number', models.CharField(max_length=255, verbose_name='Вх. номер')),
                ('rzn_date', models.CharField(max_length=255, verbose_name='Вх. дата')),
                ('dec_number', models.CharField(max_length=255, verbose_name='Исх. номер')),
                ('dec_date', models.CharField(max_length=255, verbose_name='Исх. дата')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_UPD', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('key_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rzn.taskskey')),
                ('notice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rzn.tasksnotice')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rzn.taskstype')),
            ],
        ),
    ]
