# Generated by Django 4.1 on 2022-08-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0002_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='user_id',
            new_name='user',
        ),
    ]
