# Generated by Django 4.1 on 2022-08-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0003_rename_user_id_tasks_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksdata',
            old_name='key_id',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='tasksdata',
            old_name='notice_id',
            new_name='notice',
        ),
        migrations.RenameField(
            model_name='tasksdata',
            old_name='type_id',
            new_name='type',
        ),
    ]
