# Generated by Django 4.1 on 2022-08-19 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rzn', '0004_rename_key_id_tasksdata_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksdata',
            name='date_create',
        ),
        migrations.AddField(
            model_name='tasks',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='tasksdata',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='completed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Завершено'),
        ),
    ]
