# Generated by Django 4.1 on 2022-08-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0005_remove_tasksdata_date_create_tasks_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
