# Generated by Django 4.1 on 2022-08-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0006_alter_tasksdata_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
