# Generated by Django 4.1 on 2022-08-20 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0007_alter_tasks_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rzn.tasksdata', verbose_name='Сведения'),
        ),
    ]
