# Generated by Django 4.1 on 2022-08-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0008_tasks_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksnotice',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активировать'),
        ),
    ]
