# Generated by Django 4.1 on 2022-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0010_rename_active_tasksnotice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstype',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активировать'),
        ),
    ]
