# Generated by Django 4.1 on 2022-08-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0011_taskstype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskskey',
            name='value',
            field=models.JSONField(blank=True, default={}, verbose_name='Ключ'),
        ),
    ]
