# Generated by Django 4.1 on 2022-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzn', '0012_alter_taskskey_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdata',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='date_UPD',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='dec_date',
            field=models.CharField(max_length=255, null=True, verbose_name='Исх. дата'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='dec_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Исх. номер'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='rzn_date',
            field=models.CharField(max_length=255, null=True, verbose_name='Вх. дата'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='rzn_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Вх. номер'),
        ),
        migrations.AlterField(
            model_name='tasksdata',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
