# Generated by Django 4.1 on 2022-08-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fio',
        ),
        migrations.AddField(
            model_name='customuser',
            name='comments',
            field=models.CharField(default='', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_chat_id',
            field=models.BigIntegerField(null=True, verbose_name='Чат ID'),
        ),
    ]
