# Generated by Django 4.1 on 2022-08-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_fio_customuser_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tg_first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Telegram first_name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Telegram last_name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_username',
            field=models.CharField(default='', max_length=255, verbose_name='Telegram username'),
        ),
    ]
