# Generated by Django 4.1 on 2022-08-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_tg_first_name_customuser_tg_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tg_username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_usernamess',
            field=models.CharField(default='', max_length=255, verbose_name='Telegram usernamess'),
        ),
    ]
