# Generated by Django 4.1 on 2022-08-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_tg_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tg_usernamess',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tg_username',
            field=models.CharField(default='', max_length=255, verbose_name='Telegram username'),
        ),
    ]
